@startuml
    skinparam TabSize 4
    skinparam DefaultFontName Courier
    skinparam ClassAttributeIconSize 0

    class Point
    {
        - {friend} class PointFactory;

        - float m_x;
        - float m_y;

        - Point(float x, float y);

        + float GetX() const;
        + float GetY() const;
    }

    class PointFactory
    {
        + {static} Point NewCartesian(float x, float y);
        + {static} Point NewPolar(float r, float theta);
    }
@enduml